# Generated by Django 5.2.17 on 2026-09-28 23:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='softpointprobe',
            constraint=models.CheckConstraint(condition=models.Q(('softPointC__gte', Decimal('40')), ('softPointC__lte', Decimal('120'))), name='soft_point_within_40_120'),
        ),
    ]
