# Generated by Django 5.2.17 on 2026-09-28 23:03

from decimal import Decimal

from django.db import migrations, models

PROBE_MIN = Decimal("40")
PROBE_MAX = Decimal("120")


def purge_out_of_range_probes(apps, schema_editor):
    """删除历史越界探针残行。

    这些行来自旧逻辑「先入库、后报错」产生的幻影残行，
    从未通过校验，不应留在库中，更不应出现在时间线上。
    先清干净再加 CHECK 约束。
    """
    SoftPointProbe = apps.get_model("kiln", "SoftPointProbe")
    SoftPointProbe.objects.filter(
        models.Q(softPointC__lt=PROBE_MIN) | models.Q(softPointC__gt=PROBE_MAX)
    ).delete()


def noop_reverse(apps, schema_editor):
    # 无法复原已删除的非法残行；反向迁移保持无操作。
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("kiln", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(purge_out_of_range_probes, noop_reverse),
        migrations.AddConstraint(
            model_name="softpointprobe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("softPointC__gte", PROBE_MIN),
                    ("softPointC__lte", PROBE_MAX),
                ),
                name="softpoint_within_40_120",
            ),
        ),
    ]
